#!/bin/bash

rsync -rvz --progress --delete --exclude-from=/home/jason/Projects/empirecities/wp-content/themes/empire-cities-direct/rsync-exclude.txt ~/Projects/empirecities/wp-content/themes/empire-cities-direct/ bbstage:~/public_html/empirecities/wp-content/themes/empire-cities-direct/